url: https://spatlyu.github.io/gdverse/
template:
  bootstrap: 5
  bootswatch: spacelab
  math-rendering: mathjax

navbar:
  components:
    articles:
      text: Vignettes
      menu:
      - text: Original Geographical Detector(GD)
        href: articles/GD.html
      - text: Optimal Parameters-based Geographical Detector(OPGD)
        href: articles/OPGD.html
      - text: Spatial Heterogeneity Explanation(GOZH&LESH)
        href: articles/SHEGD.html
      - text: Spatial Association Detector(SPADE)
        href: articles/SPADE.html
      - text: Interactive Detector For Spatial Associations(IDSA)
        href: articles/IDSA.html
      - text: Robust Geographical Detector&Robust Interaction Detector(RGD&RID)
        href: articles/RGDRID.html
      - text: Compare Size Effect of Spatial Units(SESU)
        href: articles/SESU.html

on:
  push:
    branches: main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    - name: Install dependencies
      run: |
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran('pkgdown')
    - name: Build site
      run: |
        Rscript -e 'pkgdown::build_site()'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
home:
  title: |
    gdverse | Geographical Detector Models
authors:
  Wenbo Lv:
    href: https://spatlyu.github.io/
  Yongze Song:
    href: https://yongzesong.com/

